apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: guestbook
    tier: frontend
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
  - port: 80
    #targetPort: 3000
  selector:
    app: guestbook
    tier: frontend