apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: guestbook
    name: frontend
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: frontend-pod
    app: guestbook